project/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


# from pybo import views          # 추가, 삭제

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('pybo/', views.index),   # views.py 파일의 index 함수를 의미
    # pybo/로 시작하는 페이지를 요청하면 pybo/urls.py 파일에서 처리
    path('pybo/', include('pybo.urls')),
    path('', views.index),
]

project/mysite/pybo/urls.py
# 여기 폴더의 url을 처리한다.

from django.urls import path

from . import views

app_name = 'pybo'  # 파일에 네임스페이스를 의미하는 app_name 변수를 지정

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name = 'detail'),
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

project/mysite/pybo/models.py
from django.db import models

# Create your models here.


# 질문 모델
class Question(models.Model):    
    subject     = models.CharField(max_length=200)
    content     = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


# 답변 모델
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

project/mysite/config/views.py
from django.shortcuts import render

# Create your views here.


from django.http import HttpResponse

def index(request):
    return HttpResponse("<h1> 메인 화면</h1>")

project/mysite/pybo/views.py
from django.shortcuts   import render, get_object_or_404, redirect
from django.utils       import timezone

# Create your views here.


# from django.http import HttpResponse
from .models            import Question, Answer

def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}

    return render(request, 'pybo/question_list.html', context)



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question} 

    return render(request, 'pybo/question_detail.html', context)



def answer_create(request, question_id):
    # pybo 답변 등록

    q = get_object_or_404(Question, pk=question_id)
    print('answer_create: ',q)
    print('request: ',request)
    print('question_id: ',question_id)
    print('--- request.POST.get(content): ', request.POST.get('content'))
    answer = Answer(question = q, 
                    content = request.POST.get('content'),
                    create_date = timezone.now())
    answer.save()
    return redirect('pybo:detail', question_id=q.id)

project/mysite/templates/base.html
{% load static %}

<!doctype html>

<html lang="ko">
<head>
    <!-- 메타 테그 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- bootstap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <!-- pybo css -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title> Hello, pybo!</title>
</head>

<body>
    <!-- 기본 템플릿에 삽입될 내용 start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿에 삽입될 내용 end -->
</body>
</html>

project/mysite/templates/pybo/question_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <!-- 질 문 -->
    <h2 class="border-bottom py-2"> {{ question.subject }} </h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>

            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>

    <!-- 답 변 -->
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }} 개의 답변이 있습니다.
    </h5>

    {% for a in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ a.content }}
            </div>

            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ a.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">

    </form>

</div>

{% endblock %}

<!-- 

<h1> {{ question.subject }} </h1>
<div>
    {{ question.content }}
</div>
<p></p>

<h5>
    {{ question.answer_set.count }} 개의 답변이 있습니다.
</h5>
-->
<!-- 답변 내용을 출력한다.  -->
<!-- <div>
    <ul>
        {% for a in question.answer_set.all %}

            <li> {{ a.content }} </li>

        {% endfor %}
    </ul>
</div> -->


<!-- 답변을 등록하는 폼 -->
<!-- <form action="{% url 'pybo:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" row="15"></textarea>
    <p></p>
    <input type="submit" value="답변등록">
</form> -->

project/mysite/templates/pybo/question_list.html
<!-- 부트스트랩 적용 -->

{% extends 'base.html' %}

{% block content %}


<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="table-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>

        <tbody>
            {% if question_list %}
                {% for q in question_list %}
                <tr>
                    <td>  {{ forloop.counter }} </td>
                    <td>
                        <a href="{% url 'pybo:detail' q.id %}">
                            {{ q.subject }}
                        </a>
                    </td>
                    <td> {{ q.create_date }} </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3"> 질문이 없습니다. </td>
                </tr>

            {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
            질문등록하기
    </a>
</div>

{% endblock %}


<!-- {% if question_list %}
    <ul>
    {% for question in question_list %}
        <li>
            <a href="{% url 'pybo:detail' question.id %}" >
                {{ question.subject }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %} -->